set(PROJECT_NAME "p101_numeric")
set(PROJECT_VERSION "0.0.1")
set(PROJECT_DESCRIPTION "Portable mathematical and random-number facilities")
set(PROJECT_LANGUAGE "C")

set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

set(STANDARD_FLAGS -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -Werror)
set(DARWIN_STANDARD_FLAGS -D_DARWIN_C_SOURCE)
set(LINUX_STANDARD_FLAGS -D_GNU_SOURCE)
set(BSD_STANDARD_FLAGS -D_BSD_SOURCE -D__BSD_VISIBLE)

set(LIBRARY_TARGETS p101_math p101_random)
set(p101_math_SOURCES src/p101_math/math.c)
set(p101_math_HEADERS include/p101_math/p101_math.h)
set(p101_math_LINK_LIBRARIES p101_error p101_env p101_c m)
set(p101_random_SOURCES src/p101_random/stdlib.c)
set(p101_random_HEADERS include/p101_random/p101_stdlib.h)
set(p101_random_LINK_LIBRARIES p101_error p101_env p101_c)
